# test
apiVersion: v1
kind: Service
metadata:
  name: simple-java-app
  labels:
    helm.sh/chart: simple-java-app-0.1.0
    app.kubernetes.io/name: simple-java-app
    app.kubernetes.io/instance: cde
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: simple-java-app
    app.kubernetes.io/instance: cde
---
# Source: cde-user-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
  labels:
    helm.sh/chart: csimple-java-app-0.1.0
    app.kubernetes.io/name: simple-java-app
    app.kubernetes.io/instance: cde
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-java-app
      app.kubernetes.io/instance: cde
  template:
    metadata:
      labels:
        helm.sh/chart: simple-java-app-0.1.0
        app.kubernetes.io/name: simple-java-app
        app.kubernetes.io/instance: cde
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: simple-java-app
          image: "ccr.ccs.tencentyun.com/wangjw/simple-java-app:v0.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
            tcpSocket:
              port: http

          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi